-- 
-- Test to create a simpel DM that can run with GeoGig
-- To be used for presentation
--

-- Copied Table: ga.g_hauptltg_abschnitt
DROP TABLE IF EXISTS ga_test.g_hauptltg_abschnitt;

CREATE TABLE ga_test.g_hauptltg_abschnitt
(
  g_katasterblattnummer_g_katasterblattnummer_katasterblattnummer character varying(30),
  system_id bigint NOT NULL,
  nenndurchmesser character varying(11),
  material character varying(15),
  verbindungsart character varying(48),
  druckabsenkungszone character varying(17),
  aktueller_status character varying(32),
  zukuenftiger_status character varying(27),
  rohrumhuellung character varying(24),
  rohrnachumhuellung character varying(24),
  verlegungsart character varying(34),
  baujahr character varying(11),
  nenndruck character varying(11),
  maximaler_betriebsdruck character varying(11),
  unterhaltspflicht character varying(17),
  vertrag character varying(17),
  zustaendigkeit character varying(34),
  sonderfunktion character varying(47),
  entstehungsform character varying(37),
  pruefturnus character varying(15),
  hersteller_rohr character varying(38),
  g_hauptleitung_leitungs_par_id character varying(10),
  baufallnummer character varying(10),
  auftragsnummer character varying(15),
  erfasst_von character varying(32),
  geaendert_von character varying(32),
  pruefer character varying(32),
  pruefverfahren character varying(32),
  pruefergebnis character varying(32),
  typ character varying(32),
  gesellschaft character varying(32),
  unterstammnummer bigint,
  datum_letzte_statusaenderung date,
  datum_der_stillegung date,
  netzdruck bigint,
  erfasst_am date,
  geaendert_am date,
  laenge_gis real,
  laenge real,
  pruefdatum date,
  skizze_pointer bigint,
  text_id bigint,
  texte_id bigint,
  strassenschluessel bigint,
  ueberarbeitungsstatus character varying(20),
  bezugslinie_darstellen_ integer,
  rauhigkeit real,
  verlustfaktor_zeta real,
  katasterblattnummer character varying(30),
  korrosionsschutz character varying(17),
  inschutznahmedatum date,
  vorgezogener_eintrag character varying(17),
  dyn_sektor character varying(64),
  gemeindename character varying(32),
  druckstufenkuerzel character varying(10),
  druckstufe character varying(15),
  dyn_korrosionsschutz character varying(64),
  strassenname character varying(48),
  ortsteil character varying(32),
  log_ueberarbeitungsstatus character varying(32),
  gemarkungsname character varying(32),
  d_leitung_in_betrieb geometry(LineString,31468),
  --beschriftung_uebersicht_in_be geometry(Point,31468),
  beschriftung_uebersicht_in_be_string text,
  beschriftung_uebersicht_in_be_just_x numeric,
  beschriftung_uebersicht_in_be_height numeric,
  beschriftung_uebersicht_in_be_just_y numeric,
  d_leitung_in_betrieb_style_info character varying(64),
  beschriftung_uebersicht_in_be_style_info character varying(64),
  beschriftung_uebersicht_in_be_ori numeric,
  bemerkungen text,
  g_katasterblattnummer_aspect character varying(30),
  g_hauptleitung_aspect character varying(10),
  bemerkung_zusatzbeschriftung text,
  rwo_id bigint[],
  sw_exported_on timestamp without time zone,
  CONSTRAINT g_hauptltg_abschnitt_pkey PRIMARY KEY (system_id)
)
WITH (
  OIDS=TRUE
);
ALTER TABLE ga_test.g_hauptltg_abschnitt
  OWNER TO admin;

CREATE INDEX sp_g_hauptltg_abschnitt_d_leitung_in_betrieb
  ON ga_test.g_hauptltg_abschnitt
  USING gist
  (d_leitung_in_betrieb);

INSERT INTO ga_test.g_hauptltg_abschnitt 
( 
  g_katasterblattnummer_g_katasterblattnummer_katasterblattnummer,
  system_id,
  nenndurchmesser,
  material,
  verbindungsart,
  druckabsenkungszone,
  aktueller_status,
  zukuenftiger_status,
  rohrumhuellung,
  rohrnachumhuellung,
  verlegungsart,
  baujahr,
  nenndruck,
  maximaler_betriebsdruck,
  unterhaltspflicht,
  vertrag,
  zustaendigkeit,
  sonderfunktion,
  entstehungsform,
  pruefturnus,
  hersteller_rohr,
  g_hauptleitung_leitungs_par_id,
  baufallnummer,
  auftragsnummer,
  erfasst_von,
  geaendert_von,
  pruefer,
  pruefverfahren,
  pruefergebnis,
  typ,
  gesellschaft,
  unterstammnummer,
  datum_letzte_statusaenderung,
  datum_der_stillegung,
  netzdruck,
  erfasst_am,
  geaendert_am,
  laenge_gis,
  laenge,
  pruefdatum,
  skizze_pointer,
  text_id,
  texte_id,
  strassenschluessel,
  ueberarbeitungsstatus,
  bezugslinie_darstellen_,
  rauhigkeit,
  verlustfaktor_zeta,
  katasterblattnummer,
  korrosionsschutz,
  inschutznahmedatum,
  vorgezogener_eintrag,
  dyn_sektor,
  gemeindename,
  druckstufenkuerzel,
  druckstufe,
  dyn_korrosionsschutz,
  strassenname,
  ortsteil,
  log_ueberarbeitungsstatus,
  gemarkungsname,
  d_leitung_in_betrieb,
  --beschriftung_uebersicht_in_be geometry(Point,31468),
  beschriftung_uebersicht_in_be_string,
  beschriftung_uebersicht_in_be_just_x,
  beschriftung_uebersicht_in_be_height,
  beschriftung_uebersicht_in_be_just_y,
  d_leitung_in_betrieb_style_info,
  beschriftung_uebersicht_in_be_style_info,
  beschriftung_uebersicht_in_be_ori,
  bemerkungen,
  g_katasterblattnummer_aspect,
  g_hauptleitung_aspect,
  bemerkung_zusatzbeschriftung,
  rwo_id,
  sw_exported_on
)
SELECT 
  g_katasterblattnummer_g_katasterblattnummer_katasterblattnummer,
  system_id,
  nenndurchmesser,
  material,
  verbindungsart,
  druckabsenkungszone,
  aktueller_status,
  zukuenftiger_status,
  rohrumhuellung,
  rohrnachumhuellung,
  verlegungsart,
  baujahr,
  nenndruck,
  maximaler_betriebsdruck,
  unterhaltspflicht,
  vertrag,
  zustaendigkeit,
  sonderfunktion,
  entstehungsform,
  pruefturnus,
  hersteller_rohr,
  g_hauptleitung_leitungs_par_id,
  baufallnummer,
  auftragsnummer,
  erfasst_von,
  geaendert_von,
  pruefer,
  pruefverfahren,
  pruefergebnis,
  typ,
  gesellschaft,
  unterstammnummer,
  datum_letzte_statusaenderung,
  datum_der_stillegung,
  netzdruck,
  erfasst_am,
  geaendert_am,
  laenge_gis,
  laenge,
  pruefdatum,
  skizze_pointer,
  text_id,
  texte_id,
  strassenschluessel,
  ueberarbeitungsstatus,
  bezugslinie_darstellen_::int,
  rauhigkeit,
  verlustfaktor_zeta,
  katasterblattnummer,
  korrosionsschutz,
  inschutznahmedatum,
  vorgezogener_eintrag,
  dyn_sektor,
  gemeindename,
  druckstufenkuerzel,
  druckstufe,
  dyn_korrosionsschutz,
  strassenname,
  ortsteil,
  log_ueberarbeitungsstatus,
  gemarkungsname,
  d_leitung_in_betrieb,
  --beschriftung_uebersicht_in_be geometry(Point,31468),
  beschriftung_uebersicht_in_be_string,
  beschriftung_uebersicht_in_be_just_x,
  beschriftung_uebersicht_in_be_height,
  beschriftung_uebersicht_in_be_just_y,
  d_leitung_in_betrieb_style_info,
  beschriftung_uebersicht_in_be_style_info,
  beschriftung_uebersicht_in_be_ori,
  bemerkungen,
  g_katasterblattnummer_aspect,
  g_hauptleitung_aspect,
  bemerkung_zusatzbeschriftung,
  rwo_id,
  sw_exported_on   
FROM ga.g_hauptltg_abschnitt WHERE d_leitung_in_betrieb && ST_MakeEnvelope(4471556,5330606,4492634,5344219,31468);

-------------------------------------------------------------------------------------
-- Copied Table: ga.g_versorgungsltg_abschnitt

DROP TABLE IF EXISTS ga_test.g_versorgungsltg_abschnitt;

CREATE TABLE ga_test.g_versorgungsltg_abschnitt
(
  g_katasterblattnummer_g_katasterblattnummer_katasterblattnummer character varying(30),
  system_id bigint NOT NULL,
  nenndurchmesser character varying(11),
  material character varying(15),
  verbindungsart character varying(48),
  verlegungsart character varying(34),
  baujahr character varying(11),
  vertrag character varying(17),
  rohrumhuellung character varying(24),
  rohrnachumhuellung character varying(24),
  korrosionsschutz character varying(17),
  nenndruck character varying(11),
  maximaler_betriebsdruck character varying(11),
  zustaendigkeit character varying(34),
  sonderfunktion character varying(47),
  entstehungsform character varying(37),
  pruefturnus character varying(15),
  hersteller_rohr character varying(38),
  aktueller_status character varying(32),
  zukuenftiger_status character varying(27),
  baufallnummer character varying(10),
  auftragsnummer character varying(15),
  erfasst_von character varying(32),
  geaendert_von character varying(32),
  pruefer character varying(32),
  pruefverfahren character varying(32),
  pruefergebnis character varying(32),
  typ character varying(32),
  gesellschaft character varying(32),
  unterstammnummer bigint,
  netzdruck bigint,
  inschutznahmedatum date,
  erfasst_am date,
  geaendert_am date,
  laenge_gis real,
  laenge real,
  pruefdatum date,
  datum_letzte_statusaenderung date,
  datum_der_stillegung date,
  ehem_rnd_nummer character varying(10),
  texte_id bigint,
  notes_id bigint,
  skizze_pointer bigint,
  strassenschluessel bigint,
  ueberarbeitungsstatus character varying(20),
  bezugslinie_darstellen_ integer,
  rauhigkeit real,
  verlustfaktor_zeta real,
  katasterblattnummer character varying(30),
  vorgezogener_eintrag character varying(17),
  dyn_sektor character varying(64),
  druckstufenkuerzel character varying(10),
  strassenname character varying(48),
  log_ueberarbeitungsstatus character varying(32),
  druckstufe character varying(15),
  gemarkungsname character varying(32),
  ortsteil character varying(32),
  dyn_korrosionsschutz character varying(64),
  gemeindename character varying(32),
  d_leitung_in_betrieb geometry(LineString,31468),
  d_leitung_in_betrieb_style_info character varying(64),
  bemerkung_zusatzbeschriftung text,
  g_katasterblattnummer_aspect character varying(30),
  bemerkungen text,
  uuid text,
  rwo_id bigint[],
  sw_exported_on timestamp without time zone,
  CONSTRAINT g_versorgungsltg_abschnitt_pkey PRIMARY KEY (system_id)
)
WITH (
  OIDS=TRUE
);
ALTER TABLE ga_test.g_versorgungsltg_abschnitt
  OWNER TO admin;

CREATE INDEX sp_g_versorgungsltg_abschnitt_d_leitung_in_betrieb
  ON ga_test.g_versorgungsltg_abschnitt
  USING gist
  (d_leitung_in_betrieb);

INSERT INTO ga_test.g_versorgungsltg_abschnitt 
(
  g_katasterblattnummer_g_katasterblattnummer_katasterblattnummer,
  system_id,
  nenndurchmesser,
  material,
  verbindungsart,
  verlegungsart,
  baujahr,
  vertrag,
  rohrumhuellung,
  rohrnachumhuellung,
  korrosionsschutz,
  nenndruck,
  maximaler_betriebsdruck,
  zustaendigkeit,
  sonderfunktion,
  entstehungsform,
  pruefturnus,
  hersteller_rohr,
  aktueller_status,
  zukuenftiger_status,
  baufallnummer,
  auftragsnummer,
  erfasst_von,
  geaendert_von,
  pruefer,
  pruefverfahren,
  pruefergebnis,
  typ,
  gesellschaft,
  unterstammnummer,
  netzdruck,
  inschutznahmedatum,
  erfasst_am,
  geaendert_am,
  laenge_gis,
  laenge,
  pruefdatum,
  datum_letzte_statusaenderung,
  datum_der_stillegung,
  ehem_rnd_nummer,
  texte_id,
  notes_id,
  skizze_pointer,
  strassenschluessel,
  ueberarbeitungsstatus,
  bezugslinie_darstellen_,
  rauhigkeit,
  verlustfaktor_zeta,
  katasterblattnummer,
  vorgezogener_eintrag,
  dyn_sektor,
  druckstufenkuerzel,
  strassenname,
  log_ueberarbeitungsstatus,
  druckstufe,
  gemarkungsname,
  ortsteil,
  dyn_korrosionsschutz,
  gemeindename,
  d_leitung_in_betrieb,
  d_leitung_in_betrieb_style_info,
  bemerkung_zusatzbeschriftung,
  g_katasterblattnummer_aspect,
  bemerkungen,
  uuid,
  rwo_id,
  sw_exported_on
) 
SELECT 
  g_katasterblattnummer_g_katasterblattnummer_katasterblattnummer,
  system_id,
  nenndurchmesser,
  material,
  verbindungsart,
  verlegungsart,
  baujahr,
  vertrag,
  rohrumhuellung,
  rohrnachumhuellung,
  korrosionsschutz,
  nenndruck,
  maximaler_betriebsdruck,
  zustaendigkeit,
  sonderfunktion,
  entstehungsform,
  pruefturnus,
  hersteller_rohr,
  aktueller_status,
  zukuenftiger_status,
  baufallnummer,
  auftragsnummer,
  erfasst_von,
  geaendert_von,
  pruefer,
  pruefverfahren,
  pruefergebnis,
  typ,
  gesellschaft,
  unterstammnummer,
  netzdruck,
  inschutznahmedatum,
  erfasst_am,
  geaendert_am,
  laenge_gis,
  laenge,
  pruefdatum,
  datum_letzte_statusaenderung,
  datum_der_stillegung,
  ehem_rnd_nummer,
  texte_id,
  notes_id,
  skizze_pointer,
  strassenschluessel,
  ueberarbeitungsstatus,
  bezugslinie_darstellen_::int,
  rauhigkeit,
  verlustfaktor_zeta,
  katasterblattnummer,
  vorgezogener_eintrag,
  dyn_sektor,
  druckstufenkuerzel,
  strassenname,
  log_ueberarbeitungsstatus,
  druckstufe,
  gemarkungsname,
  ortsteil,
  dyn_korrosionsschutz,
  gemeindename,
  d_leitung_in_betrieb,
  d_leitung_in_betrieb_style_info,
  bemerkung_zusatzbeschriftung,
  g_katasterblattnummer_aspect,
  bemerkungen,
  uuid::text,
  rwo_id,
  sw_exported_on
FROM ga.g_versorgungsltg_abschnitt WHERE d_leitung_in_betrieb && ST_MakeEnvelope(4471556,5330606,4492634,5344219,31468);

-------------------------------------------------------------------------------------
-- Copied Table: ga.g_hausanschluss
DROP TABLE IF EXISTS ga_test.g_hausanschluss;

CREATE TABLE ga_test.g_hausanschluss
(
  system_id bigint NOT NULL,
  anschlusstyp character varying(27),
  zustand character varying(10),
  anschlussort character varying(40),
  aktueller_status character varying(32),
  zukuenftiger_status character varying(27),
  absperrorgan character varying(20),
  mantelrohr character varying(17),
  ausziehsicherung character varying(17),
  elektrische_trennstelle character varying(15),
  entlueftungsanschluss character varying(17),
  mauerdurchfuehrung character varying(11),
  pruefturnus character varying(15),
  baujahr character varying(11),
  entstehungsform character varying(37),
  hausnummer character varying(16),
  erfasst_von character varying(32),
  geaendert_von character varying(32),
  hersteller character varying(32),
  pruefer character varying(32),
  pruefverfahren character varying(32),
  pruefergebnis character varying(32),
  knotenbezeichnung bigint,
  einleitungsnummer bigint,
  anzahl_der_anschluesse bigint,
  datum_letzte_statusaenderung date,
  datum_der_stillegung date,
  pruefungsdatum date,
  erfasst_am date,
  geaendert_am date,
  pruefdatum date,
  strassenschluessel bigint,
  notes_id bigint,
  skizze_pointer bigint,
  hoehe_ueber_nn real,
  geschosszahl integer,
  zustaendigkeit character varying(34),
  akquiriert_durch character varying(10),
  druckmangelsicherung character varying(15),
  mitversorgte_ha character varying(6),
  gemeindename character varying(32),
  versorgender_ha character varying(64),
  ortsteil character varying(32),
  gemarkungsname character varying(32),
  strassenname character varying(48),
  flurstuecksnummer character varying(32),
  -- position_absperreinrichtung_betr geometry(Point,31468),
  -- position_druckmangelsicherung geometry(Point,31468),
  position_hausanschluss_in_betri geometry(Point,31468),
  position_hausanschluss_in_betri_mirror integer,
  position_hausanschluss_in_betri_ori numeric,
  -- position_absperreinrichtung_betr_mirror boolean,
  -- position_absperreinrichtung_betr_style_info character varying(64),
  -- position_druckmangelsicherung_ori numeric,
  -- position_absperreinrichtung_betr_scale numeric,
  position_hausanschluss_in_betri_scale numeric,
  -- position_absperreinrichtung_betr_ori numeric,
  position_hausanschluss_in_betri_style_info character varying(64),
  -- position_druckmangelsicherung_style_info character varying(64),
  -- position_druckmangelsicherung_scale numeric,
  -- position_druckmangelsicherung_mirror boolean,
  bemerkungen text,
  uuid text,
  rwo_id bigint[],
  sw_exported_on timestamp without time zone,
  CONSTRAINT g_hausanschluss_pkey PRIMARY KEY (system_id)
)
WITH (
  OIDS=TRUE
);

CREATE INDEX sp_g_hausanschluss_position_hausanschluss_in_betri
  ON ga_test.g_hausanschluss
  USING gist
  (position_hausanschluss_in_betri);

INSERT INTO ga_test.g_hausanschluss 
 (
  system_id,
  anschlusstyp,
  zustand,
  anschlussort,
  aktueller_status,
  zukuenftiger_status,
  absperrorgan,
  mantelrohr,
  ausziehsicherung,
  elektrische_trennstelle,
  entlueftungsanschluss,
  mauerdurchfuehrung,
  pruefturnus,
  baujahr,
  entstehungsform,
  hausnummer,
  erfasst_von,
  geaendert_von,
  hersteller,
  pruefer,
  pruefverfahren,
  pruefergebnis,
  knotenbezeichnung,
  einleitungsnummer,
  anzahl_der_anschluesse,
  datum_letzte_statusaenderung,
  datum_der_stillegung,
  pruefungsdatum,
  erfasst_am,
  geaendert_am,
  pruefdatum,
  strassenschluessel,
  notes_id,
  skizze_pointer,
  hoehe_ueber_nn,
  geschosszahl,
  zustaendigkeit,
  akquiriert_durch,
  druckmangelsicherung,
  mitversorgte_ha,
  gemeindename,
  versorgender_ha,
  ortsteil,
  gemarkungsname,
  strassenname,
  flurstuecksnummer,
  -- position_absperreinrichtung_betr,
  -- position_druckmangelsicherung),
  position_hausanschluss_in_betri,
  position_hausanschluss_in_betri_mirror,
  position_hausanschluss_in_betri_ori,
  -- position_absperreinrichtung_betr_mirror,
  -- position_absperreinrichtung_betr_style_info,
  -- position_druckmangelsicherung_ori numeric,
  -- position_absperreinrichtung_betr_scale,
  position_hausanschluss_in_betri_scale,
  -- position_absperreinrichtung_betr_ori,
  position_hausanschluss_in_betri_style_info,
  -- position_druckmangelsicherung_style_info,
  -- position_druckmangelsicherung_scale,
  -- position_druckmangelsicherung_mirror,
  bemerkungen,
  uuid,
  rwo_id,
  sw_exported_on
)
SELECT 
  system_id,
  anschlusstyp,
  zustand,
  anschlussort,
  aktueller_status,
  zukuenftiger_status,
  absperrorgan,
  mantelrohr,
  ausziehsicherung,
  elektrische_trennstelle,
  entlueftungsanschluss,
  mauerdurchfuehrung,
  pruefturnus,
  baujahr,
  entstehungsform,
  hausnummer,
  erfasst_von,
  geaendert_von,
  hersteller,
  pruefer,
  pruefverfahren,
  pruefergebnis,
  knotenbezeichnung,
  einleitungsnummer,
  anzahl_der_anschluesse,
  datum_letzte_statusaenderung,
  datum_der_stillegung,
  pruefungsdatum,
  erfasst_am,
  geaendert_am,
  pruefdatum,
  strassenschluessel,
  notes_id,
  skizze_pointer,
  hoehe_ueber_nn,
  geschosszahl,
  zustaendigkeit,
  akquiriert_durch,
  druckmangelsicherung,
  mitversorgte_ha,
  gemeindename,
  versorgender_ha,
  ortsteil,
  gemarkungsname,
  strassenname,
  flurstuecksnummer,
  -- position_absperreinrichtung_betr,
  -- position_druckmangelsicherung),
  position_hausanschluss_in_betri,
  position_hausanschluss_in_betri_mirror::int,
  position_hausanschluss_in_betri_ori,
  -- position_absperreinrichtung_betr_mirror,
  -- position_absperreinrichtung_betr_style_info,
  -- position_druckmangelsicherung_ori numeric,
  -- position_absperreinrichtung_betr_scale,
  position_hausanschluss_in_betri_scale,
  -- position_absperreinrichtung_betr_ori,
  position_hausanschluss_in_betri_style_info,
  -- position_druckmangelsicherung_style_info,
  -- position_druckmangelsicherung_scale,
  -- position_druckmangelsicherung_mirror,
  bemerkungen,
  uuid::text,
  rwo_id,
  sw_exported_on
FROM ga.g_hausanschluss WHERE position_hausanschluss_in_betri && ST_MakeEnvelope(4471556,5330606,4492634,5344219,31468);

-------------------------------------------------------------------------------------
-- Copied Table: ga.g_abzweig

DROP TABLE IF EXISTS ga_test.g_abzweig;

CREATE TABLE ga_test.g_abzweig
(
  system_id bigint NOT NULL,
  bauart character varying(23),
  ueberdeckungsstatus character varying(11),
  umhuellung character varying(24),
  druckstufe character varying(15),
  schieberstellung_ventil character varying(16),
  aktueller_status character varying(32),
  zukuenftiger_status character varying(27),
  entstehungsform character varying(37),
  pruefturnus character varying(15),
  baujahr character varying(11),
  erfasst_von character varying(32),
  geaendert_von character varying(32),
  pruefer character varying(32),
  pruefverfahren character varying(32),
  pruefergebnis character varying(32),
  typ character varying(32),
  hersteller character varying(32),
  knotenbezeichnung bigint,
  hoehe_ueber_nn real,
  ueberdeckung real,
  datum_letzte_statusaenderung date,
  datum_der_stillegung date,
  erfasst_am date,
  geaendert_am date,
  pruefdatum date,
  skizze_pointer bigint,
  text_id bigint,
  bedienbar integer,
  gasstroemungswaechter integer,
  akquiriert_durch character varying(10),
  gasstroemungswaechter2 integer,
  -- beschr_gswaechter_in_betrieb geometry(Point,31468),
  -- beschriftung_ueberdeckung_in_be geometry(Point,31468),
  -- position_ventil_in_betrieb geometry(Point,31468),
  -- beschriftung_hoehenwert_in_betr geometry(Point,31468),
  -- beschr_gswaechter2 geometry(Point,31468),
  d_position_in_betrieb geometry(Point,31468),
  -- beschr_gswaechter2_height numeric,
  -- beschriftung_ueberdeckung_in_be_string text,
  -- beschriftung_ueberdeckung_in_be_just_y numeric,
  -- position_ventil_in_betrieb_style_info character varying(64),
  d_position_in_betrieb_scale numeric,
  -- beschr_gswaechter_in_betrieb_string text,
  -- position_ventil_in_betrieb_mirror integer,
  -- position_ventil_in_betrieb_scale numeric,
  -- beschriftung_hoehenwert_in_betr_ori numeric,
  -- beschriftung_hoehenwert_in_betr_just_y numeric,
  -- beschr_gswaechter2_ori numeric,
  -- beschr_gswaechter_in_betrieb_style_info character varying(64),
  -- beschriftung_ueberdeckung_in_be_ori numeric,
  -- beschriftung_hoehenwert_in_betr_style_info character varying(64),
  -- beschr_gswaechter2_just_y numeric,
  d_position_in_betrieb_ori real,
  -- beschriftung_hoehenwert_in_betr_string text,
  -- beschr_gswaechter2_string text,
  -- beschr_gswaechter2_just_x numeric,
  d_position_in_betrieb_mirror integer,
  -- beschr_gswaechter_in_betrieb_just_y numeric,
  -- position_ventil_in_betrieb_ori numeric,
  -- beschriftung_ueberdeckung_in_be_just_x numeric,
  d_position_in_betrieb_style_info character varying(64),
  -- beschriftung_hoehenwert_in_betr_just_x numeric,
  -- beschr_gswaechter2_style_info character varying(64),
  -- beschr_gswaechter_in_betrieb_just_x numeric,
  -- beschriftung_hoehenwert_in_betr_height numeric,
  -- beschriftung_ueberdeckung_in_be_style_info character varying(64),
  -- beschr_gswaechter_in_betrieb_ori numeric,
  -- beschriftung_ueberdeckung_in_be_height numeric,
  -- beschr_gswaechter_in_betrieb_height numeric,
  bemerkungen text,
  uuid text,
  rwo_id bigint[],
  sw_exported_on timestamp without time zone,
  CONSTRAINT g_abzweig_pkey PRIMARY KEY (system_id)
)
WITH (
  OIDS=TRUE
);

CREATE INDEX sp_g_abzweig_d_position_in_betrieb
  ON ga_test.g_abzweig
  USING gist
  (d_position_in_betrieb);

INSERT INTO ga_test.g_abzweig
(
  system_id,
  bauart,
  ueberdeckungsstatus,
  umhuellung,
  druckstufe,
  schieberstellung_ventil,
  aktueller_status,
  zukuenftiger_status,
  entstehungsform,
  pruefturnus,
  baujahr,
  erfasst_von,
  geaendert_von,
  pruefer,
  pruefverfahren,
  pruefergebnis,
  typ,
  hersteller,
  knotenbezeichnung,
  hoehe_ueber_nn,
  ueberdeckung,
  datum_letzte_statusaenderung,
  datum_der_stillegung,
  erfasst_am,
  geaendert_am,
  pruefdatum,
  skizze_pointer,
  text_id,
  bedienbar,
  gasstroemungswaechter,
  akquiriert_durch,
  gasstroemungswaechter2,
  -- beschr_gswaechter_in_betrieb,
  -- beschriftung_ueberdeckung_in_be,
  -- position_ventil_in_betrieb,
  -- beschriftung_hoehenwert_in_betr,
  -- beschr_gswaechter2,
  d_position_in_betrieb,
  -- beschr_gswaechter2_height,
  -- beschriftung_ueberdeckung_in_be_string,
  -- beschriftung_ueberdeckung_in_be_just_y numeric,
  -- position_ventil_in_betrieb_style_info,
  d_position_in_betrieb_scale,
  -- beschr_gswaechter_in_betrieb_string,
  -- position_ventil_in_betrieb_mirror,
  -- position_ventil_in_betrieb_scale,
  -- beschriftung_hoehenwert_in_betr_ori,
  -- beschriftung_hoehenwert_in_betr_just_y,
  -- beschr_gswaechter2_ori,
  -- beschr_gswaechter_in_betrieb_style_info,
  -- beschriftung_ueberdeckung_in_be_ori,
  -- beschriftung_hoehenwert_in_betr_style_info,
  -- beschr_gswaechter2_just_y,
  d_position_in_betrieb_ori,
  -- beschriftung_hoehenwert_in_betr_string,
  -- beschr_gswaechter2_string,
  -- beschr_gswaechter2_just_x,
  d_position_in_betrieb_mirror,
  -- beschr_gswaechter_in_betrieb_just_y,
  -- position_ventil_in_betrieb_ori,
  -- beschriftung_ueberdeckung_in_be_just_x numeric,
  d_position_in_betrieb_style_info,
  -- beschriftung_hoehenwert_in_betr_just_x,
  -- beschr_gswaechter2_style_info,
  -- beschr_gswaechter_in_betrieb_just_x,
  -- beschriftung_hoehenwert_in_betr_height numeric,
  -- beschriftung_ueberdeckung_in_be_style_info,
  -- beschr_gswaechter_in_betrieb_ori,
  -- beschriftung_ueberdeckung_in_be_height,
  -- beschr_gswaechter_in_betrieb_height,
  bemerkungen,
  uuid,
  rwo_id,
  sw_exported_on
) 
SELECT 
  system_id,
  bauart,
  ueberdeckungsstatus,
  umhuellung,
  druckstufe,
  schieberstellung_ventil,
  aktueller_status,
  zukuenftiger_status,
  entstehungsform,
  pruefturnus,
  baujahr,
  erfasst_von,
  geaendert_von,
  pruefer,
  pruefverfahren,
  pruefergebnis,
  typ,
  hersteller,
  knotenbezeichnung,
  hoehe_ueber_nn,
  ueberdeckung,
  datum_letzte_statusaenderung,
  datum_der_stillegung,
  erfasst_am,
  geaendert_am,
  pruefdatum,
  skizze_pointer,
  text_id,
  bedienbar::int,
  gasstroemungswaechter::int,
  akquiriert_durch,
  gasstroemungswaechter2::int,
  -- beschr_gswaechter_in_betrieb,
  -- beschriftung_ueberdeckung_in_be,
  -- position_ventil_in_betrieb,
  -- beschriftung_hoehenwert_in_betr,
  -- beschr_gswaechter2,
  d_position_in_betrieb,
  -- beschr_gswaechter2_height,
  -- beschriftung_ueberdeckung_in_be_string,
  -- beschriftung_ueberdeckung_in_be_just_y numeric,
  -- position_ventil_in_betrieb_style_info,
  d_position_in_betrieb_scale,
  -- beschr_gswaechter_in_betrieb_string,
  -- position_ventil_in_betrieb_mirror,
  -- position_ventil_in_betrieb_scale,
  -- beschriftung_hoehenwert_in_betr_ori,
  -- beschriftung_hoehenwert_in_betr_just_y,
  -- beschr_gswaechter2_ori,
  -- beschr_gswaechter_in_betrieb_style_info,
  -- beschriftung_ueberdeckung_in_be_ori,
  -- beschriftung_hoehenwert_in_betr_style_info,
  -- beschr_gswaechter2_just_y,
  d_position_in_betrieb_ori::real,
  -- beschriftung_hoehenwert_in_betr_string,
  -- beschr_gswaechter2_string,
  -- beschr_gswaechter2_just_x,
  d_position_in_betrieb_mirror::int,
  -- beschr_gswaechter_in_betrieb_just_y,
  -- position_ventil_in_betrieb_ori,
  -- beschriftung_ueberdeckung_in_be_just_x numeric,
  d_position_in_betrieb_style_info,
  -- beschriftung_hoehenwert_in_betr_just_x,
  -- beschr_gswaechter2_style_info,
  -- beschr_gswaechter_in_betrieb_just_x,
  -- beschriftung_hoehenwert_in_betr_height numeric,
  -- beschriftung_ueberdeckung_in_be_style_info,
  -- beschr_gswaechter_in_betrieb_ori,
  -- beschriftung_ueberdeckung_in_be_height,
  -- beschr_gswaechter_in_betrieb_height,
  bemerkungen,
  uuid::text,
  rwo_id,
  sw_exported_on
FROM ga.g_abzweig WHERE d_position_in_betrieb && ST_MakeEnvelope(4471556,5330606,4492634,5344219,31468);

-------------------------------------------------------------------------------------
-- Copied Table: ga.g_anschlussltg_abschnitt

DROP TABLE IF EXISTS ga_test.g_anschlussltg_abschnitt;

CREATE TABLE ga_test.g_anschlussltg_abschnitt
(
  g_katasterblattnummer_g_katasterblattnummer_katasterblattnummer character varying(30),
  g_hausanschluss_g_hausanschluss_system_id bigint,
  system_id bigint NOT NULL,
  anschlussart character varying(33),
  nenndurchmesser character varying(11),
  material character varying(15),
  verbindungsart character varying(48),
  aktueller_status character varying(32),
  zukuenftiger_status character varying(27),
  rohrumhuellung character varying(24),
  rohrnachumhuellung character varying(24),
  verlegungsart character varying(34),
  korrosionsschutz character varying(17),
  baujahr character varying(11),
  nenndruck character varying(11),
  maximaler_betriebsdruck character varying(11),
  zustaendigkeit character varying(34),
  entstehungsform character varying(37),
  pruefturnus character varying(15),
  hersteller_rohr character varying(38),
  baufallnummer character varying(10),
  auftragsnummer character varying(15),
  erfasst_von character varying(32),
  geaendert_von character varying(32),
  pruefer character varying(32),
  pruefverfahren character varying(32),
  pruefergebnis character varying(32),
  typ character varying(32),
  gesellschaft character varying(32),
  unterstammnummer bigint,
  netzdruck bigint,
  datum_letzte_statusaenderung date,
  datum_der_stillegung date,
  inschutznahmedatum date,
  erfasst_am date,
  geaendert_am date,
  laenge_gis real,
  laenge real,
  pruefdatum date,
  skizze_pointer bigint,
  text_id bigint,
  texte_id bigint,
  ueberarbeitungsstatus character varying(20),
  bezugslinie_darstellen_ integer,
  rauhigkeit real,
  verlustfaktor_zeta real,
  katasterblattnummer character varying(30),
  akquiriert_durch character varying(10),
  vorgezogener_eintrag character varying(17),
  strassenname character varying(48),
  gemeindename character varying(32),
  druckstufenkuerzel character varying(10),
  druckstufe character varying(15),
  strassenschluessel character varying(32),
  dyn_korrosionsschutz character varying(64),
  ortsteil character varying(32),
  log_ueberarbeitungsstatus character varying(32),
  d_leitung_in_betrieb geometry(LineString,31468),
  d_leitung_in_betrieb_style_info character varying(64),
  g_hausanschluss_aspect character varying(16),
  g_katasterblattnummer_aspect character varying(30),
  bemerkung_zusatzbeschriftung text,
  bemerkungen text,
  uuid text,
  rwo_id bigint[],
  sw_exported_on timestamp without time zone,
  CONSTRAINT g_anschlussltg_abschnitt_pkey PRIMARY KEY (system_id)
)
WITH (
  OIDS=TRUE
);

CREATE INDEX sp_g_anschlussltg_abschnitt_d_leitung_in_betrieb
  ON ga_test.g_anschlussltg_abschnitt
  USING gist
  (d_leitung_in_betrieb); 

INSERT INTO ga_test.g_anschlussltg_abschnitt
(
  g_katasterblattnummer_g_katasterblattnummer_katasterblattnummer,
  g_hausanschluss_g_hausanschluss_system_id,
  system_id,
  anschlussart,
  nenndurchmesser,
  material,
  verbindungsart,
  aktueller_status,
  zukuenftiger_status,
  rohrumhuellung,
  rohrnachumhuellung,
  verlegungsart,
  korrosionsschutz,
  baujahr,
  nenndruck,
  maximaler_betriebsdruck,
  zustaendigkeit,
  entstehungsform,
  pruefturnus,
  hersteller_rohr,
  baufallnummer,
  auftragsnummer,
  erfasst_von,
  geaendert_von,
  pruefer,
  pruefverfahren,
  pruefergebnis,
  typ,
  gesellschaft,
  unterstammnummer,
  netzdruck,
  datum_letzte_statusaenderung,
  datum_der_stillegung,
  inschutznahmedatum,
  erfasst_am,
  geaendert_am,
  laenge_gis,
  laenge,
  pruefdatum,
  skizze_pointer,
  text_id,
  texte_id,
  ueberarbeitungsstatus,
  bezugslinie_darstellen_,
  rauhigkeit,
  verlustfaktor_zeta,
  katasterblattnummer,
  akquiriert_durch,
  vorgezogener_eintrag,
  strassenname,
  gemeindename,
  druckstufenkuerzel,
  druckstufe,
  strassenschluessel,
  dyn_korrosionsschutz,
  ortsteil,
  log_ueberarbeitungsstatus,
  d_leitung_in_betrieb,
  d_leitung_in_betrieb_style_info,
  g_hausanschluss_aspect,
  g_katasterblattnummer_aspect,
  bemerkung_zusatzbeschriftung,
  bemerkungen,
  uuid,
  rwo_id,
  sw_exported_on
) 
SELECT 
  g_katasterblattnummer_g_katasterblattnummer_katasterblattnummer,
  g_hausanschluss_g_hausanschluss_system_id,
  system_id,
  anschlussart,
  nenndurchmesser,
  material,
  verbindungsart,
  aktueller_status,
  zukuenftiger_status,
  rohrumhuellung,
  rohrnachumhuellung,
  verlegungsart,
  korrosionsschutz,
  baujahr,
  nenndruck,
  maximaler_betriebsdruck,
  zustaendigkeit,
  entstehungsform,
  pruefturnus,
  hersteller_rohr,
  baufallnummer,
  auftragsnummer,
  erfasst_von,
  geaendert_von,
  pruefer,
  pruefverfahren,
  pruefergebnis,
  typ,
  gesellschaft,
  unterstammnummer,
  netzdruck,
  datum_letzte_statusaenderung,
  datum_der_stillegung,
  inschutznahmedatum,
  erfasst_am,
  geaendert_am,
  laenge_gis,
  laenge,
  pruefdatum,
  skizze_pointer,
  text_id,
  texte_id,
  ueberarbeitungsstatus,
  bezugslinie_darstellen_::int,
  rauhigkeit,
  verlustfaktor_zeta,
  katasterblattnummer,
  akquiriert_durch,
  vorgezogener_eintrag,
  strassenname,
  gemeindename,
  druckstufenkuerzel,
  druckstufe,
  strassenschluessel,
  dyn_korrosionsschutz,
  ortsteil,
  log_ueberarbeitungsstatus,
  d_leitung_in_betrieb,
  d_leitung_in_betrieb_style_info,
  g_hausanschluss_aspect,
  g_katasterblattnummer_aspect,
  bemerkung_zusatzbeschriftung,
  bemerkungen,
  uuid::text,
  rwo_id,
  sw_exported_on
FROM ga.g_anschlussltg_abschnitt WHERE d_leitung_in_betrieb && ST_MakeEnvelope(4471556,5330606,4492634,5344219,31468);


